config:
  send_anonymous_usage_stats: false
  use_experimental_parser: true
  fail_fast: false

drug_risk_pipeline:
  target: dev

  outputs:
    dev:
      type: snowflake
      account: "chizcdk-zm51873"
      user: "SANDHIYABK"
      password: "9jcwpx9kGwfyAC6"
      role: ACCOUNTADMIN
      database: DRUG_INTEL_DB
      warehouse: COMPUTE_WH
      schema: STAGING
      threads: 4